apiVersion: v1
kind: Deployment
metadata:
  name: vertex-deploy
  labels:
    app: myvertexapp
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myvertexapp
  template:
     metadata:
       labels: 
         app: myvertexapp
     spec:
       containers:
        - name: myvertexapp-container
          image:  laxmikant7007/myvertexapp:1
          ports:
            - containerPort: 8080